// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHm1OPU0iRa4dLWa56ZTVCTi6oRbrpYII',
    appId: '1:933436923771:web:f257949e43f9f7f522e7de',
    messagingSenderId: '933436923771',
    projectId: 'sama-alerts',
    authDomain: 'sama-alerts.firebaseapp.com',
    storageBucket: 'sama-alerts.firebasestorage.app',
    measurementId: 'G-WZJQCW9X7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpcvKRLcQ-eO2CfYLKqo9mgUi799WxTvc',
    appId: '1:933436923771:android:cdc8d955e892342422e7de',
    messagingSenderId: '933436923771',
    projectId: 'sama-alerts',
    storageBucket: 'sama-alerts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRmN3UUl_WcTheaApTITyxZrNaPMNMbA',
    appId: '1:933436923771:ios:58799acbeffb78e822e7de',
    messagingSenderId: '933436923771',
    projectId: 'sama-alerts',
    storageBucket: 'sama-alerts.firebasestorage.app',
    iosBundleId: 'com.example.samafirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMRmN3UUl_WcTheaApTITyxZrNaPMNMbA',
    appId: '1:933436923771:ios:58799acbeffb78e822e7de',
    messagingSenderId: '933436923771',
    projectId: 'sama-alerts',
    storageBucket: 'sama-alerts.firebasestorage.app',
    iosBundleId: 'com.example.samafirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHm1OPU0iRa4dLWa56ZTVCTi6oRbrpYII',
    appId: '1:933436923771:web:8ba81696572861cd22e7de',
    messagingSenderId: '933436923771',
    projectId: 'sama-alerts',
    authDomain: 'sama-alerts.firebaseapp.com',
    storageBucket: 'sama-alerts.firebasestorage.app',
    measurementId: 'G-ER6FDHFNPV',
  );

}